print('--- Me fale sobre o seu nascimento ---')
dia= input('Qual é o dia do seu nascimento ?')
mes= input('Qual é o mês do seu nascimento ?')
ano= input('Qual é o ano do seu nascimento ?')
print(f'Seu dia de nascimento é {dia}, no mês{mes} e agora o seu ano é {ano}')