a = input('Digite alguma coisa')
print('O primitivo desse valor é ', type(a))
print('Só tem espacos ? ', a.isspace())
print('É um número ? ', a.isnumeric())
print('É alfabetico ? ', a.isalpha())
print('É alfanumérico? ' ,a.isalnum())
print('Está em maiúsculos? ' ,a.isupper())
print('Está em minúsculo ?' ,a.islower())
print('Está capitalizada ?' ,a.istitle())
